/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.regex.Pattern;

import org.eclipse.kura.gpio.KuraGPIODescription;
import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOPin;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Common methods for libgpiod-based GPIO services
 */
public abstract class LibGpiodGPIOService {

    private static final Logger logger = LoggerFactory.getLogger(LibGpiodGPIOService.class);

    protected static final String GPIO_CHIP_NAME = "gpiochip";
    private static final Pattern GPIO_CHIP_PATTERN = Pattern.compile("^" + GPIO_CHIP_NAME + "\\d+$");

    protected final List<KuraGPIODescription> availablePinDescriptions = new CopyOnWriteArrayList<>();
    protected final Map<KuraGPIODescription, KuraGPIOPin> pinCache = new ConcurrentHashMap<>();

    private static final KuraGPIODirection DEFAULT_DIRECTION = KuraGPIODirection.INPUT;
    private static final KuraGPIOMode DEFAULT_MODE = KuraGPIOMode.INPUT_PULL_UP;
    private static final KuraGPIOTrigger DEFAULT_TRIGGER = KuraGPIOTrigger.NONE;

    protected AtomicBoolean initialized = new AtomicBoolean(false);

    /**
     * Initialize the GPIO service by discovering available GPIO chips and pins
     */
    public void initialize() {
        synchronized (this) {
            if (this.initialized.get()) {
                return;
            }

            discoverGPIOChips();
            this.initialized.set(true);
        }
    }

    /**
     * Discover all available GPIO chips and their pins
     */
    private void discoverGPIOChips() {
        this.availablePinDescriptions.clear();

        File devDir = new File(getDeviceFolderPath());
        if (!devDir.exists() || !devDir.isDirectory()) {
            return;
        }

        File[] chipFiles = devDir.listFiles((dir, name) -> GPIO_CHIP_PATTERN.matcher(name).matches());
        if (chipFiles == null || chipFiles.length == 0) {
            return;
        }

        Arrays.sort(chipFiles, (a, b) -> {
            int numA = LibGpiodPin.extractChipNumber(a.getName());
            int numB = LibGpiodPin.extractChipNumber(b.getName());
            return Integer.compare(numA, numB);
        });

        for (File chipFile : chipFiles) {
            discoverChipPins(chipFile.getAbsolutePath());
        }
    }

    /**
     * Discover pins for a specific GPIO chip
     */
    protected abstract void discoverChipPins(String chipPath);

    public KuraGPIOPin getPinByName(String pinName) {
        return getPinByName(pinName, DEFAULT_DIRECTION, DEFAULT_MODE, DEFAULT_TRIGGER);
    }

    public KuraGPIOPin getPinByName(String pinName, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        List<KuraGPIOPin> pins = getPins(pinName, direction, mode, trigger);
        return pins.get(0);
    }

    public KuraGPIOPin getPinByTerminal(int terminal) {
        return getPinByTerminal(terminal, DEFAULT_DIRECTION, DEFAULT_MODE, DEFAULT_TRIGGER);
    }

    public KuraGPIOPin getPinByTerminal(int terminal, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        if (terminal < 0) {
            throw new IllegalArgumentException("Terminal number must be non-negative");
        }

        initialize();

        int chipNumber = terminal / 1000;
        int offset = terminal % 1000;
        String chipPath = getDeviceFolderPath() + GPIO_CHIP_NAME + chipNumber;

        if (!isValidPin(chipPath, offset)) {
            throw new IllegalArgumentException("Invalid terminal: " + terminal);
        }

        return getPin(chipNumber, offset, direction, mode, trigger);
    }

    public List<KuraGPIOPin> getPins(String name) {
        return getPins(name, DEFAULT_DIRECTION, DEFAULT_MODE, DEFAULT_TRIGGER);
    }

    public List<KuraGPIOPin> getPins(String name, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Pin name cannot be null or empty");
        }

        initialize();

        // Retrieve gpio descriptions from available pins that matches the given name.
        List<KuraGPIODescription> nameMatchingDescriptions = new ArrayList<>();
        this.availablePinDescriptions.forEach(description -> {
            Optional<String> pinName = description.getName();
            if (pinName.isPresent() && pinName.get().equals(name)) {
                nameMatchingDescriptions.add(description);
            }
        });

        if (nameMatchingDescriptions.isEmpty()) {
            throw new IllegalArgumentException("Pin not found: " + name);
        }

        List<KuraGPIOPin> pins = new ArrayList<>();

        // Try to get the cached pins, otherwise create a new one.
        nameMatchingDescriptions.forEach(description -> {
            Optional<KuraGPIOPin> cachedPin = getCachedPin(description.getController(), description.getLine(),
                    direction, mode, trigger);
            if (cachedPin.isPresent()) {
                pins.add(cachedPin.get());
            } else {
                KuraGPIOPin pin = createPin(description, direction, mode, trigger);
                this.pinCache.put(description, pin);
                pins.add(pin);
            }
        });

        return pins;
    }

    public KuraGPIOPin getPin(int controller, int line) {
        return getPin(controller, line, DEFAULT_DIRECTION, DEFAULT_MODE, DEFAULT_TRIGGER);
    }

    public KuraGPIOPin getPin(int controller, int line, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        if (controller < 0 || line < 0) {
            throw new IllegalArgumentException("Controller and line numbers must be non-negative");
        }

        initialize();

        // Check if the pin description is present in the available pin list and get the
        // full description (i.e. name).
        KuraGPIODescription description = new KuraGPIODescription(controller, line);
        if (!this.availablePinDescriptions.contains(description)) {
            throw new IllegalArgumentException(
                    "Pin not found: controller=" + controller + ", line=" + line);
        }
        for (KuraGPIODescription availableDescription : this.availablePinDescriptions) {
            if (availableDescription.equals(description)) {
                description = availableDescription;
                break;
            }
        }

        Optional<KuraGPIOPin> cachedPin = getCachedPin(controller, line, direction, mode, trigger);
        if (cachedPin.isPresent()) {
            return cachedPin.get();
        }

        KuraGPIOPin pin = createPin(description, direction, mode, trigger);

        this.pinCache.put(description, pin);

        return pin;
    }

    public Map<Integer, String> getAvailablePins() {
        initialize();
        Map<Integer, String> pins = new HashMap<>();
        this.availablePinDescriptions
                .forEach(description -> pins.put(description.getController() * 1000 + description.getLine(),
                        description.getName().orElse("UNKNOWN")));
        return pins;
    }

    public List<KuraGPIODescription> getAvailablePinDescriptions() {
        initialize();
        return this.availablePinDescriptions;
    }

    /**
     * Verify if a pin exists on the specified chip
     */
    protected abstract boolean isValidPin(String chipPath, int offset);

    protected abstract KuraGPIOPin createPin(KuraGPIODescription description, KuraGPIODirection direction,
            KuraGPIOMode mode, KuraGPIOTrigger trigger);

    private Optional<KuraGPIOPin> getCachedPin(int controller, int line, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        KuraGPIODescription description = new KuraGPIODescription(controller, line);
        KuraGPIOPin cachedPin = this.pinCache.get(description);
        if (cachedPin != null) {
            if (pinHasSameConfiguration(cachedPin, direction, mode, trigger)) {
                return Optional.of(cachedPin);
            } else {
                try {
                    cachedPin.close();
                } catch (IOException e) {
                    logger.error("Error closing pin {}:{}: {}", description.getController(), description.getLine(),
                            e.getMessage());
                }
                this.pinCache.remove(description);
            }
        }
        return Optional.empty();
    }

    private boolean pinHasSameConfiguration(KuraGPIOPin pin, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        return pin.getDirection() == direction && pin.getMode() == mode && pin.getTrigger() == trigger;
    }

    /**
     * Clear pin cache - useful for testing or when pin configurations change
     */
    public void clearCache() {
        this.pinCache.clear();
    }

    /**
     * Refresh pin discovery - rescans all chips
     */
    public void refresh() {
        this.initialized.set(false);
        clearCache();
        initialize();
    }

    protected String getDeviceFolderPath() {
        return "/dev/";
    }

    public Map<KuraGPIODescription, KuraGPIOPin> getPinCache() {
        return this.pinCache;
    }

}